// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAay63Q6ri88uLWASKLys2p9yohVr3S_2s',
    appId: '1:774519681336:web:f64f35041f84639c52d1cd',
    messagingSenderId: '774519681336',
    projectId: 'fish-farm-app-cc432',
    authDomain: 'fish-farm-app-cc432.firebaseapp.com',
    storageBucket: 'fish-farm-app-cc432.firebasestorage.app',
    measurementId: 'G-P5ZMBCZCZG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9qxgE9cvnnEFlpLZguF1lzpUYh13s_sE',
    appId: '1:774519681336:ios:685bf7ceb20619ba52d1cd',
    messagingSenderId: '774519681336',
    projectId: 'fish-farm-app-cc432',
    storageBucket: 'fish-farm-app-cc432.firebasestorage.app',
    iosBundleId: 'com.example.fishFarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9qxgE9cvnnEFlpLZguF1lzpUYh13s_sE',
    appId: '1:774519681336:ios:685bf7ceb20619ba52d1cd',
    messagingSenderId: '774519681336',
    projectId: 'fish-farm-app-cc432',
    storageBucket: 'fish-farm-app-cc432.firebasestorage.app',
    iosBundleId: 'com.example.fishFarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAay63Q6ri88uLWASKLys2p9yohVr3S_2s',
    appId: '1:774519681336:web:2712c6ca3bd9b39652d1cd',
    messagingSenderId: '774519681336',
    projectId: 'fish-farm-app-cc432',
    authDomain: 'fish-farm-app-cc432.firebaseapp.com',
    storageBucket: 'fish-farm-app-cc432.firebasestorage.app',
    measurementId: 'G-2PY8V3DTQ6',
  );
}
